### ISSUE TITLE
Update Request - 1.12.2

### ISSUE THREAD

**Issue by XMxmx111** [connor135246/Campfire-Backport#10]
Are there any plans in porting this mod to MC 1.12.2?

**Comment by connor135246** [comment]
Probably not, sorry.
You could try porting it forward yourself if you want.

**Comment by TheOldOne822** [comment]
https://www.curseforge.com/minecraft/mc-mods/just-a-campfire

**Comment by Roadhog360** [comment]
Should this not be open because the question has been conclusively answered?
