### ISSUE TITLE
Cauldron Support

### ISSUE THREAD

**Issue by DrParadox7** [connor135246/Campfire-Backport#12]
Certain mods such as Thaumcraft 4 and Witchery check if they are above fire in order to function:

`if(super.worldObj.getBlock(super.xCoord,` super.yCoord - 1, super.zCoord).getMaterial() != Material.fire) {`

I was wondering if it is possible to fool them into believing that the campfire is an actual fire.

This would be especially useful for those packs that gate flint and steel behind some complicated steel production.

Not to mention how great it would look:
![image](https://user-images.githubusercontent.com/47131096/108569267-80ec5480-7303-11eb-8e54-d82c33f2c14e.png)

**Comment by connor135246** [comment]
Added in v1.8.2
