### ISSUE TITLE
[Feature Request]Botania Automation

### ISSUE THREAD

**Issue by DrParadox7** [connor135246/Campfire-Backport#13]
Botania allows the ignition of blocks using Mana Bursts shot through the [Mana Lens: Kindle](https://ftbwiki.org/Mana_Lens:_Kindle) - ([**code**](https://github.com/Vazkii/Botania/blob/1.7.10-final/src/main/java/vazkii/botania/common/item/lens/LensFire.java)).

This would allow for long-range automation of campfire through Hopperhocks, Rannucarpus and redstone.

Such a setup can already be achieved via dispensers but it would make for fine-looking contraption, especially in regards to the regen effect some campfires can provide (useful when setting up a [Gaia Arena](https://www.youtube.com/watch?v=lCV0QlBzy5E)).

![image](https://user-images.githubusercontent.com/47131096/109382456-71a77100-78d8-11eb-9dd7-f81e3ffcc243.png)

**Comment by connor135246** [comment]
Added in v1.8.3
Mana bursts from kindle lenses light campfires.

**Comment by DrParadox7** [comment]
I have got to respect your dedication to this project. Albeit small, the attention to detail is astonishing.
