### ISSUE TITLE
Thaumcraft campfirebackportmixins error, cannot heat up crucible

### ISSUE THREAD

**Issue by tyrael93** [connor135246/Campfire-Backport#15]
Just a single error line, but I just noticed this. 
>[main/ERROR] [campfirebackportmixins]: An error occurred when searching for the mod "Thaumcraft". 

The crucible does not seem to be getting heated up properly. I expect this is also happening for the thaumatorium as well. TC support is enabled for the mod.
![2021-04-18_13 23 34](https://user-images.githubusercontent.com/5557920/115143741-699ebe80-a049-11eb-8307-de0d61c3eed4.png)

Thanks in advance for any help on the subject, this is the modlist I am currently using.
https://paste.ee/p/RdPwv

**Comment by connor135246** [comment]
It might have something to do with SpongeMixins again.
Your modlist has SpongeMixins-1.3.1 but I can't seem to find a version above 1.2.0. Where did you get that version?

**Comment by tyrael93** [comment]
Oh, here http://jenkins.usrv.eu:8080/job/Sponge-Mixins/

**Comment by connor135246** [comment]
Thanks.
Unfortunately Sponge Mixins doesn't seem to be the cause, I can't replicate your issue.
I'm hoping that it's a more simple issue and isn't related to some weird mod interactions. I've made a couple changes, so can I ask you to be a beta tester?
https://github.com/connor135246/Campfire-Backport/releases/tag/v1.8.4-pre

**Comment by tyrael93** [comment]
Of course, thank you for taking time for this issue. 
>[main/INFO] [campfirebackportmixins]: Found "thaumcraftneiplugin-1.7.10-1.7a.jar". "Thaumcraft" mixins will be applied.
Hey looks like that worked! :+1: 
After actual testing, the cauldron heats up as intended.
Thanks again!
