### ISSUE TITLE
Support for Energy NBT Data

### ISSUE THREAD

**Issue by DrParadox7** [connor135246/Campfire-Backport#17]
I am attempting to make the [Flux Igniter](https://ftbwiki.org/Flux_Igniter) able to ignite campfires when right clicked, at the cost of 400 RF.

However, as it stores its durability values as NBT data, it is proving to be rather challenging to do so with Minetweaker:
`<ThermalExpansion:igniter>.withTag({Energy: 77600})`

The only option I currently have is to enable ignition free of charge or disable it completely.
Is there a way around this, which I might not be aware of?

**Comment by connor135246** [comment]
> Is there a way around this, which I might not be aware of?  

No, there wasn't really a way around this before.
But in v1.9, you can do this:
`mods.campfirebackport.addCampfireIgnitor("both", <ThermalExpansion:igniter>.onlyWithTagAdvanced("{Energy: 400 (cost)}"), "none");`
