### ISSUE TITLE
where's the smoke

### ISSUE THREAD

**Issue by KibaTheBarbarian** [connor135246/Campfire-Backport#18]
no smoke going on in the latest version

**Comment by connor135246** [comment]
Campfires are still making smoke for me.
Can you post your mod list?

**Comment by KibaTheBarbarian** [comment]
i test it useing just the campfirebackport latest version  and the latest 1.7.10 Forge and vanilla Minecraft settings  the same testing I did with the campfire eating food bug

**Comment by connor135246** [comment]
Found it, it was a mistake in the bit that colors the smoke. 
It'll be in the next update, for now you can fix it by turning the config option "Colorful Campfire Smoke" on for both campfire types.

**Comment by connor135246** [comment]
And the fix is now released in v1.9.
