### ISSUE TITLE
SpongeMixins console error: net.minecraft.entity.projectile.EntityPotion

### ISSUE THREAD

**Issue by tyrael93** [connor135246/Campfire-Backport#19]
Sorry to be back so soon, but it does look like the latest version of spongemixins is throwing problems with throwing potions.

http://jenkins.usrv.eu:8080/job/Sponge-Mixins/lastBuild/

Error log:
https://pastebin.com/WpaHhd2b

Cheers and thanks for any input on this!

Edit: after several checks, it looks like it happens with builds dating as far back as February, which was weird, and on further inspections disabling another just installed mixin offender mod fixed the issue. Sorry to bother!

**Comment by connor135246** [comment]
Apparently mixins don't like int array arrays.
Not really sure why it worked fine as long as no other mixins targeted EntityPotion, though.

**Comment by tyrael93** [comment]
Neat, thanks.
