### ISSUE TITLE
Campfire recipes using fluids get stuck in the campfire

### ISSUE THREAD

**Issue by DrParadox7** [connor135246/Campfire-Backport#22]
Buckets, tanks and any fluid containers, after completion of a recipe are stuck within campfires when using fluid methods found [here](https://github.com/connor135246/Campfire-Backport/wiki/%5BWorking-with-Fluid-Containers-in-CraftTweaker%5D).
![2021-12-01_13 12 51](https://user-images.githubusercontent.com/47131096/144240613-b876083f-ec6f-46f0-a7df-1be9249aefaa.png)

**Comment by connor135246** [comment]
Fixed in v1.10
