### ISSUE TITLE
(Shaders) Smoke particles change brightness depending on the visibility of the campfire

### ISSUE THREAD

**Issue by kotmatross28729** [connor135246/Campfire-Backport#27]
### If you have shaders and you raise your head up until you can't see the campfire, then the smoke particles will start to change brightness (darken) but if you put the campfire back in your field of view, it will become normal again

https://user-images.githubusercontent.com/110309314/211854352-94e46cce-da16-45ea-9277-2291ba9447ef.mp4

https://user-images.githubusercontent.com/110309314/211854365-929df42b-3456-471c-b287-f0b316ea0cee.mp4

**Comment by connor135246** [comment]
What shaders are you using?

**Comment by kotmatross28729** [comment]
It seems to happen to everyone, Sildur's Vibrant was used in the video, but separately I also use bsl (also happens).

**Comment by connor135246** [comment]
Should be fixed in v1.10.1!

**Comment by kotmatross28729** [comment]
Yes, it's working fine now. Thank you!
