### ISSUE TITLE
Allow Campfire Extinguishers to be removed via CraftTweaker.

### ISSUE THREAD

**Issue by MagmaBro123** [connor135246/Campfire-Backport#28]
Title.

mods.campfirebackport.removeCampfireIgnitor(<minecraft:writteb_book>); does not work, and I see no other mentions of removing things, only adding.

**Comment by connor135246** [comment]
The default extinguishers and ignitors are in the config. Instead of using CraftTweaker, you remove them by deleting them from the config.

I added some new information to the wiki to explain how this works.
https://github.com/connor135246/Campfire-Backport/wiki/Recipes-Overview

**Comment by MagmaBro123** [comment]
Ah, sorry.

**Comment by connor135246** [comment]
Nah, I'm the one who's sorry. Until now I didn't explain anywhere that it works like that.
