### ISSUE TITLE
Github release is corrupted

### ISSUE THREAD

**Issue by DrParadox7** [connor135246/Campfire-Backport#29]
Using the mixin release v1.10.1 found [here](https://github.com/connor135246/Campfire-Backport/releases/tag/v1.10.1) the game will crash with:
`Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)`
[fml-client-latest.txt](https://github.com/connor135246/Campfire-Backport/files/11927182/fml-client-latest.txt)

However, the version published on CF ([found here](https://legacy.curseforge.com/minecraft/mc-mods/campfire-backport/files/4611674)) works fine.

These seem to be 2 unique files, looking at their respective SHA-256:

**CF Hash:**
`1f004032b65e551afc8e1dec6cfdc2c55eded4b2c6964fc241017ca26802b760`
**Github Hash:**
`7a8c3bd0679a94ba39bbaae6956444618fccd72d85725aa5c02c466959cc55e0`

Please consider replacing the latest Github release with the CF file

**Comment by connor135246** [comment]
Thank you for letting me know! It's fixed now. I don't know how it happened.
