### ISSUE TITLE
Oh yes i do have some ideas:

### ISSUE THREAD

**Issue by HRudyPlayZ** [connor135246/Campfire-Backport#3]
- An option to make certain biomes / dimensions automatically burn out campfires (there could be 2 options that would be formatted like dimension: campfire[both,soulsoil,normal]: timer (optional) )
- An option to make campfires even burn out in the inventory (i don't know if that's the case already)
- CraftTweaker compatibility

Very great mod, keep up the good work :P

**Comment by connor135246** [comment]
I've added all of these as of v1.7!
