### ISSUE TITLE
Recipe request -- Upcoming Et Futurum Requiem nether update

### ISSUE THREAD

**Issue by Roadhog360** [connor135246/Campfire-Backport#30]
This is an exceedingly simple request. Similar to Netherlicious, I am doing my own Nether backport. It will add soul soil and I simply request my block, `etfuturum:soul_soul` to be checked for as a valid crafting ingredient when that comes out. Netherlicious' soul soil should keep priority if present, however.
Alternatively, I raise the alternative idea of a new OreDictionary tag be created that I could add my block to. If this tag is populated with anything it'll use the 1st entry of that OreDictionary list.

**Comment by connor135246** [comment]
Sure.
How about `soulSoil` as the oredict?

**Comment by Roadhog360** [comment]
Works for me. And for the drop you could make it just use the first item in this tag. This should cover any mods that add a soul dirt block in the future. Maybe a soulSand tag too?

**Comment by connor135246** [comment]
>Maybe a soulSand tag too?
Good idea. It looks like other mods such as Botania use that oredict, so I'll use it too.
