### ISSUE TITLE
Netherlicious Support Request - Other Fire Variants

### ISSUE THREAD

**Issue by KAMKEEL** [connor135246/Campfire-Backport#31]
Hey @connor135246 !

Would it be possible to add Netherlicious support to add the other fire types if Netherlicious is installed? It's a very popular Nether Backport / Nether Reimagination Mod that adds old and new features to the nether in 1.7.10.

![image](https://github.com/connor135246/Campfire-Backport/assets/28842281/10835284-ebc8-4701-a45e-77597f255291)

**Comment by connor135246** [comment]
It would be cool, but would require a lot of changes.
For example, all the config options are based around there being just two types of campfires. The way the config is laid out would have to be entirely changed. I'm not sure what that would look like yet. 

So I'll say that it's possible, but don't hold your breath.

**Comment by KAMKEEL** [comment]
I think just making the new flame variants take after the Soul Variant if they are also Nether Flames.

**Comment by connor135246** [comment]
Huh, somehow I never thought of doing that.
I'll make the Netherlicious campfires and have them inherit config options from the soul campfire.

**Comment by connor135246** [comment]
Sorry for the long wait! I've added them in v1.11.
