### ISSUE TITLE
GTNH NEI support.

### ISSUE THREAD

**Issue by MagmaBro123** [connor135246/Campfire-Backport#32]
Title.

Campfire Backport's tabs in NEI aren't set up to work in GTNH's NEI correctly.

![2023-10-14_12 35 48](https://github.com/connor135246/Campfire-Backport/assets/51277766/7b4fa9c9-b4e4-4e4e-b634-827e2c3f7ff6)

Happens with and without other mods besides required mods.

**Comment by connor135246** [comment]
I've actually already added support in a recent commit.
The release is coming soon-ish.

**Comment by MagmaBro123** [comment]
Would also like to mention a few other issues,

Campfire Backport's "fire" renders weirdly, normally this is a 3D fire.

![2023-10-14_16 17 38](https://github.com/connor135246/Campfire-Backport/assets/51277766/42fae5b7-66ca-42a9-aa91-fac0106f8402)

(Might be caused by Hodgepodge)

Also seems Hodgepodge's speedupAnimations config completely breaks Campfire Backport's fire animations.

**Comment by connor135246** [comment]
"Soon-ish" ended up being pretty long. Sorry! I've finally released v1.11.

**Comment by MagmaBro123** [comment]
> "Soon-ish" ended up being pretty long. Sorry! I've finally released v1.11.

Lol, you're good. Glad this is finally dealt with.
