### ISSUE TITLE
Feature request!

### ISSUE THREAD

**Issue by brandyyn** [connor135246/Campfire-Backport#35]
hi, i'd really like to use this, but my idea with this mod would be to have the campfires spawn in villages lit, players can right click them to set their spawnpoint there and have campfires be uncraftable/unobtainable, but for this i need a config option to have a campfire structure spawn in a village, unless you know of a way for me to do that?

i also would really like a config to disable the ability to cook anything using the campfires

Edit: Nevermind!! I made my own structure using recurrent complex, I still need that config option to stop campfires from being able to cook things and it would be nice to have a config to set normal right click to set spawn rather than crouch right click!

**Comment by connor135246** [comment]
To stop the campfire from being able to cook things, see [here](https://github.com/connor135246/Campfire-Backport/wiki/Recipes-Overview#removing-recipes).

For right-clicking vs crouch-right-clicking, well, such a small difference doesn't seem worth it to make a whole config option for...

**Comment by brandyyn** [comment]
> For right-clicking vs crouch-right-clicking, well, such a small difference doesn't seem worth it to make a whole config option for...

please 🥺

**Comment by connor135246** [comment]
> please 🥺

Ok, I will stop being lazy and do it.

**Comment by brandyyn** [comment]
@connor135246 could u push the update 🥺

**Comment by connor135246** [comment]
Pushed!
