### ISSUE TITLE
What happened to Foxfire and Shadow Campfires? They're no longer present in 1.10.1. (No options for re-enabling them exist either.)

### ISSUE THREAD

**Issue by MagmaBro123** [connor135246/Campfire-Backport#36]

**Comment by connor135246** [comment]
They were never in 1.10.1. They are in the latest version which is 1.11.

**Comment by MagmaBro123** [comment]
Ah, whoops. Not sure why 1.11 isn't on CurseForge or Modrinth yet.

**Comment by connor135246** [comment]
For some reason CurseForge has put it "Under Manual Review". Not sure why, I don't think this ever happened before.
It's up on Modrinth.
