### ISSUE TITLE
Crash when extinguishing/igniting campfire using dispenser with Backhand installed

### ISSUE THREAD

**Issue by huihiuhuai** [connor135246/Campfire-Backport#39]
https://pastebin.com/TqXR2YGN

**Comment by huihiuhuai** [comment]
yes yes, only dispenser

**Comment by Roadhog360** [comment]
I think what he's trying to say is that the game crashes with Backhand *installed* and using a Dispenser, it's not actually from using the offhand directly.

**Comment by connor135246** [comment]
Looks like this has been fixed in the GTNH fork of Backhand.
https://github.com/GTNewHorizons/Backhand/issues/17
