### ISSUE TITLE
[Feature Request] Let .transformFluid more useful.

### ISSUE THREAD

**Issue by song682** [connor135246/Campfire-Backport#41]
Can `.transformFluid` add a function that can let it add/increase the amout of fluid? I also had a template.  
`.transformFluid(String increaseOrDecrease, String fluidName, int minAmount, @Optional Boolean reuse)`  
`String increaseOrDecrease` can let the amout of fluid increase or decrase.  
This is depended on you. You can add it or turn it down.

**Comment by connor135246** [comment]
Done in v1.11.2!  
I split it into two different commands: `.drainFluid` to remove fluid, and `.fillFluid` to add fluid. More details on the [wiki](https://github.com/connor135246/Campfire-Backport/wiki/%5BWorking-with-Fluid-Containers-in-CraftTweaker%5D).

**Comment by song682** [comment]
Thanks
