### ISSUE TITLE
Campfire backport incompatibility with FalseTweaks experimental threaded rendering

### ISSUE THREAD

**Issue by brandyyn** [connor135246/Campfire-Backport#42]
![image](https://github.com/user-attachments/assets/cafa3a74-f2d8-4abb-9c8b-452ab7659069)

![image](https://github.com/user-attachments/assets/ae3262ae-44eb-44c3-9502-b20c7bfd7c5f)
![image](https://github.com/user-attachments/assets/68b0b38d-ae58-45b6-9694-46db46d70e2a)

{campfirebackport-1.7.10-1.11.2+nomixin}

**Comment by FalsePattern** [comment]
I've pinpointed the issue:
https://github.com/connor135246/Campfire-Backport/blob/c2faf0d487ff3be0dca685083c88115aff56702d/src/main/java/connor135246/campfirebackport/client/rendering/RenderBlockCampfire.java#L246
This line needs to be replaced with: 
```java
boolean lighting = doDraw && GL11.glGetBoolean(GL11.GL_LIGHTING);
```
To suppress the opengl call when not in a draw-secure environment.

**Comment by brandyyn** [comment]
@connor135246 I would submit a PR but I can't get your mod to build in my workspace.

**Comment by connor135246** [comment]
> I've pinpointed the issue:
> 
> https://github.com/connor135246/Campfire-Backport/blob/c2faf0d487ff3be0dca685083c88115aff56702d/src/main/java/connor135246/campfirebackport/client/rendering/RenderBlockCampfire.java#L246
> 
> This line needs to be replaced with:
> 
> ```java
> boolean lighting = doDraw && GL11.glGetBoolean(GL11.GL_LIGHTING);
> ```
> 
> To suppress the opengl call when not in a draw-secure environment.

Thanks. Glad it's a simple fix.

> @connor135246 I would submit a PR but I can't get your mod to build in my workspace.

Probably a dependency issue. I'll make the build instructions more clear about versions, sorry.

**Comment by brandyyn** [comment]
> > I've pinpointed the issue:
> > https://github.com/connor135246/Campfire-Backport/blob/c2faf0d487ff3be0dca685083c88115aff56702d/src/main/java/connor135246/campfirebackport/client/rendering/RenderBlockCampfire.java#L246
> > 
> > This line needs to be replaced with:
> > ```java
> > boolean lighting = doDraw && GL11.glGetBoolean(GL11.GL_LIGHTING);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To suppress the opengl call when not in a draw-secure environment.
> 
> Thanks. Glad it's a simple fix.
> 


When you get the time please release the fix :D
