### ISSUE TITLE
Incorrect Example on wiki

### ISSUE THREAD

**Issue by BBoldt** [connor135246/Campfire-Backport#7]
https://github.com/connor135246/Campfire-Backport/wiki/CraftTweaker-%5BBurn-Out-Biome-&-Dimension-Timers%5D

In your examples, addBurnOutRule should be addBurnOutTimer

Took me a sec to realize what I was doing wrong haha

**Comment by BBoldt** [comment]
Maybe I'm still misunderstanding, this is not working for me:

campfire.zs:
`
mods.campfirebackport.addBurnOutTimer("both", null, -28, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -29, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -30, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -132, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -134, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -136, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -137, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -138, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -139, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -140, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -144, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -147, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -149, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -150, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -151, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -1024, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -1025, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -1050, 0);
mods.campfirebackport.addBurnOutTimer("both", null, -1051, 0);`

These are the dimensions I have in my pack:

`ID,Provider ID,Provider Class Name
-1051,-1051,galaxyspace.systems.BarnardsSystem.planets.barnardaE.dimension.WorldProviderBarnardaE_WE
-1050,-1050,galaxyspace.systems.BarnardsSystem.planets.barnardaC.dimension.WorldProviderBarnardaC_WE
-1025,-1025,galaxyspace.systems.ACentauriSystem.planets.proximaB.dimension.WorldProviderProximaB
-1024,-1024,galaxyspace.systems.SolarSystem.moons.miranda.dimension.WorldProviderMiranda
-151,-151,galaxyspace.systems.SolarSystem.planets.venus.dimension.WorldProviderVenus
-150,-150,galaxyspace.systems.SolarSystem.moons.triton.dimension.WorldProviderTriton
-149,-149,galaxyspace.systems.SolarSystem.moons.titan.dimension.WorldProviderTitan_WE
-147,-147,galaxyspace.systems.SolarSystem.planets.pluto.dimension.WorldProviderPluto
-144,-144,galaxyspace.systems.SolarSystem.planets.mercury.dimension.WorldProviderMercury
-140,-140,galaxyspace.systems.SolarSystem.planets.kuiperbelt.dimension.WorldProviderKuiper
-139,-139,galaxyspace.systems.SolarSystem.moons.io.dimension.WorldProviderIo
-138,-138,galaxyspace.systems.SolarSystem.moons.ganymede.dimension.WorldProviderGanymede
-137,-137,galaxyspace.systems.SolarSystem.moons.europa.dimension.WorldProviderEuropa
-136,-136,galaxyspace.systems.SolarSystem.moons.enceladus.dimension.WorldProviderEnceladus
-134,-134,galaxyspace.systems.SolarSystem.planets.ceres.dimension.WorldProviderCeres
-132,-132,galaxyspace.systems.SolarSystem.moons.callisto.dimension.WorldProviderCallisto
-112,-112,com.rwtema.extrautils.worldgen.endoftime.WorldProviderEndOfTime
-100,-100,com.rwtema.extrautils.worldgen.Underdark.WorldProviderUnderdark
-73,-73,makeo.gadomancy.common.utils.world.WorldProviderTCEldrich
-66,-66,lumien.randomthings.Handler.Spectre.WorldProviderSpectre
-42,-42,thaumcraft.common.lib.world.dim.WorldProviderOuter
-39,-39,com.emoniph.witchery.dimension.WorldProviderMirror
-38,-38,com.emoniph.witchery.dimension.WorldProviderTorment
-37,-37,com.emoniph.witchery.dimension.WorldProviderDreamWorld
-30,-30,micdoodle8.mods.galacticraft.planets.asteroids.dimension.WorldProviderAsteroids
-29,-29,micdoodle8.mods.galacticraft.planets.mars.dimension.WorldProviderMars
-28,-28,micdoodle8.mods.galacticraft.core.dimension.WorldProviderMoon
-19,-19,thaumic.tinkerer.common.dim.WorldProviderBedrock
-7,-777,twilightforest.world.WorldProviderTwilightForest
-1,-1,DelirusCrux.Netherlicious.Dimension.NetherWorldProvider
0,0,biomesoplenty.common.world.WorldProviderSurfaceBOP
1,1,chylex.hee.world.WorldProviderHardcoreEnd
2,2,org.dave.CompactMachines.machines.world.WorldProviderMachines
4,4,com.gildedgames.the_aether.world.AetherWorldProvider
42,42,tombenpotter.sanguimancy.world.WorldProviderSoulNetworkDimension
`

**Comment by connor135246** [comment]
> In your examples, addBurnOutRule should be addBurnOutTimer

Fixed, thanks.

> Maybe I'm still misunderstanding, this is not working for me:

My bad, looks like I made a mistake in the part of the code that counts down the timer. If it starts at 0, it gets stuck and never does anything. I'll fix this in the next update (and add Galacticraft oxygen compatibility), but for now setting your timers to 1 instead of 0 should work fine.

...Though there is another minor problem you might've noticed. When you first launch Minecraft there are some MineTweaker errors about how some dimensions aren't registered, but doing "/minetweaker reload" fixes that. It seems Galacticraft doesn't register its dimensions immediately and instead waits until a world is loaded. That'll also be fixed next update, but for now you'll have to use "/minetweaker reload" at least once for your burn out timers to go through.

**Comment by connor135246** [comment]
As of v1.8:
Timer bug fixed, timers that start at zero now finish immediately as they should
Dimension registering bug fixed, burn out timers don't require that the dimension has been registered already
Github wiki and in-game wiki (the one you get from /campfirebackport dumpinfo) fixed
