### ISSUE TITLE
Compatibility request: Galacticraft Oxygen

### ISSUE THREAD

**Issue by BBoldt** [connor135246/Campfire-Backport#8]
I don't know how hard this would be to implement, but it would be really cool if campfires knew about oxygen so I wouldn't have to add burnout timers to every GC dimension. Also it would be cool (and totally safe) to be able to light campfires in oxygen sealed rooms.

I found this looking at their API:
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/block/IOxygenReliantBlock.java

**Comment by connor135246** [comment]
Added in v1.8
Also added Advanced Rocketry compatibility for good measure
